### ISSUE TITLE
Add Docker to Test

### ISSUE THREAD

**Issue by GranadaFreak** [GranadaFreak/granadafreak.github.io#2]
## Description

Add Docker with Nginx to be able to test locally in a controlled environment.

## Tasks

- [x] Add Docker with Nginx
- [x] Make Nginx receive the Code
- [x] Add a Makefile

## Tests

- [x] Check that Docker works Locally

**Comment by GranadaFreak** [comment]
### LGTM
