### ISSUE TITLE
Design Changes

### ISSUE THREAD

**Issue by GranadaFreak** [GranadaFreak/granadafreak.github.io#3]
## Description

Changes to the current Web to improve the user experience. It involves changes to the texts, removing some sections and making small style changes.

## Tasks

- [ ] Remove "Alerts" and "Events" from the Home Page
- [ ] General Text Review
- [ ] General Review of Links
- [ ] Delete "Next Events"
- [ ] Delete "Forms"

## Tests

- [ ] Check the Website Locally
